### ISSUE TITLE
Change some text

### ISSUE THREAD

**Issue by elena20ruiz** [hackupc/hackstart#8]
Change some text from spelling mistakes and better explanations:

- [x] In HOW IS THE PITCH FORMAT?: Change `2 minute` for `2 minutes`
- [x] On first text: `in one *of* the best regions in Europe, Barcelona.`

**Comment by AlbertSuarez** [comment]
`Networking` activity actually starts at 1PM, not 2PM.

**Comment by AlbertSuarez** [comment]
Done in #14.
